- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
    owner: vagrant
  with_items: directories
  tags: [nginx]

- name: Container is running
  docker:
    image: jwilder/nginx-proxy
    name: nginx
    state: running
    ports: "{{ ports }}"
    volumes: "{{ volumes }}"
  when: not log_to_syslog is defined
  tags: [nginx]

- name: Container is running
  docker:
    image: nginx:alpine
    name: nginx
    state: running
    ports: "{{ ports }}"
    volumes: "{{ volumes }}"
    log_driver: syslog
    log_opt:
      syslog-tag: nginx
  when: log_to_syslog is defined
  tags: [nginx]
