- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
    owner: vagrant
  with_items: directories
  tags: [nodejs]

- name: Files are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: files
  register: result
  tags: [nodejs]

- name: Container is running
  docker:
    image: nginx
    name: nodejs
    state: reloaded
    ports: "{{ ports }}"
    volumes: "{{ volumes }}"
  tags: [nodejs]
