- name: Update cache
  apt: update_cache=yes
  tags: [common]
  
- name: HTTPS Support
  apt:
    name: apt-transport-https
    force: yes
  tags: [common]

- name: Certificates support
  apt:
    name: ca-certificates
    force: yes
  tags: [common]

- name: JQ is present
  apt:
    name: jq
    force: yes
  tags: [common]
